name: Release

on:
  release:
    types: [published]

jobs:
  release-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: ZIP Component Dir
        run: |
          cd ${{ github.workspace }}/custom_components/hassbox_notify
          zip -r hassbox_notify.zip ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/hassbox_notify/hassbox_notify.zip
          asset_name: hassbox_notify.zip
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload zip to OSS
        uses: tvrcgo/upload-to-oss@master
        with:
          key-id: ${{ secrets.ALIYUN_OSS_ACCESS_KEY_ID }}
          key-secret: ${{ secrets.ALIYUN_OSS_ACCESS_KEY_SECRET }}
          region: ${{ secrets.ALIYUN_OSS_REGION }}
          bucket: ${{ secrets.ALIYUN_OSS_BUCKET }}
          assets: |
            ${{ github.workspace }}/install.sh:/hassbox-notify
            ${{ github.workspace }}/custom_components/hassbox_notify/hassbox_notify.zip:/hassbox_notify.zip
            ${{ github.workspace }}/custom_components/hassbox_notify/hassbox_notify.zip:/integration/hass-box/hassbox-notify/${{ github.ref_name }}/hassbox_notify.zip
